"""adjuste ideas table

Revision ID: 2264bc9036f6
Revises: d3bbe5004b17
Create Date: 2024-11-07 21:11:07.194066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2264bc9036f6'
down_revision: Union[str, None] = 'd3bbe5004b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
