# Generated by Django 5.1.2 on 2024-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_ideas_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='user',
        ),
        migrations.AlterField(
            model_name='idea',
            name='num_genius',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='num_stupid',
            field=models.BigIntegerField(default=0),
        ),
    ]
