# Generated by Django 5.1.2 on 2024-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_remove_idea_user_alter_idea_num_genius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
